# Bambu Lab RFID tag constants
# Based on: https://github.com/Bambu-Research-Group/RFID-Tag-Guide/blob/main/BambuLabRfid.md

# Total size of Mifare Classic 1K tag
TAG_TOTAL_SIZE = 1024

# Block positions (Block number * 16)
# Block 0 - UID and Tag Manufacturer Data (Read-only)
BLOCK_0_POS = 0 * 16
UID_POS = BLOCK_0_POS + 0
UID_LEN = 4

# Block 1 - Tray Info Index
BLOCK_1_POS = 1 * 16
MATERIAL_VARIANT_ID_POS = BLOCK_1_POS + 0
MATERIAL_VARIANT_ID_LEN = 8
MATERIAL_ID_POS = BLOCK_1_POS + 8
MATERIAL_ID_LEN = 8

# Block 2 - Filament Type
BLOCK_2_POS = 2 * 16
FILAMENT_TYPE_POS = BLOCK_2_POS + 0
FILAMENT_TYPE_LEN = 16

# Block 4 - Detailed Filament Type
BLOCK_4_POS = 4 * 16
DETAILED_FILAMENT_TYPE_POS = BLOCK_4_POS + 0
DETAILED_FILAMENT_TYPE_LEN = 16

# Block 5 - Spool Weight, Color Code, Filament Diameter
BLOCK_5_POS = 5 * 16
COLOR_RGBA_POS = BLOCK_5_POS + 0
COLOR_RGBA_LEN = 4
SPOOL_WEIGHT_POS = BLOCK_5_POS + 4
SPOOL_WEIGHT_LEN = 2
FILAMENT_DIAMETER_POS = BLOCK_5_POS + 8
FILAMENT_DIAMETER_LEN = 4

# Block 6 - Temperatures and Drying Info
BLOCK_6_POS = 6 * 16
DRYING_TEMP_POS = BLOCK_6_POS + 0
DRYING_TEMP_LEN = 2
DRYING_TIME_POS = BLOCK_6_POS + 2
DRYING_TIME_LEN = 2
BED_TEMP_TYPE_POS = BLOCK_6_POS + 4
BED_TEMP_TYPE_LEN = 2
BED_TEMP_POS = BLOCK_6_POS + 6
BED_TEMP_LEN = 2
HOTEND_MAX_TEMP_POS = BLOCK_6_POS + 8
HOTEND_MAX_TEMP_LEN = 2
HOTEND_MIN_TEMP_POS = BLOCK_6_POS + 10
HOTEND_MIN_TEMP_LEN = 2

# Block 8 - X Cam Info, Nozzle Diameter
BLOCK_8_POS = 8 * 16
XCAM_INFO_POS = BLOCK_8_POS + 0
XCAM_INFO_LEN = 12
NOZZLE_DIAMETER_POS = BLOCK_8_POS + 12
NOZZLE_DIAMETER_LEN = 4

# Block 9 - Tray UID
BLOCK_9_POS = 9 * 16
TRAY_UID_POS = BLOCK_9_POS + 0
TRAY_UID_LEN = 16

# Block 10 - Spool Width
BLOCK_10_POS = 10 * 16
SPOOL_WIDTH_POS = BLOCK_10_POS + 4
SPOOL_WIDTH_LEN = 2

# Block 12 - Production Date/Time
BLOCK_12_POS = 12 * 16
PRODUCTION_DATETIME_POS = BLOCK_12_POS + 0
PRODUCTION_DATETIME_LEN = 16

# Block 13 - Short Production Date/Time
BLOCK_13_POS = 13 * 16
SHORT_PRODUCTION_DATETIME_POS = BLOCK_13_POS + 0
SHORT_PRODUCTION_DATETIME_LEN = 16

# Block 14 - Filament Length
BLOCK_14_POS = 14 * 16
FILAMENT_LENGTH_POS = BLOCK_14_POS + 4
FILAMENT_LENGTH_LEN = 2

# Block 16 - Extra Color Info
BLOCK_16_POS = 16 * 16
FORMAT_IDENTIFIER_POS = BLOCK_16_POS + 0
FORMAT_IDENTIFIER_LEN = 2
COLOR_COUNT_POS = BLOCK_16_POS + 2
COLOR_COUNT_LEN = 2
SECOND_COLOR_POS = BLOCK_16_POS + 4
SECOND_COLOR_LEN = 4

# Format identifiers for Block 16
FORMAT_EMPTY = 0x0000
FORMAT_COLOR_INFO = 0x0002
